const appProperty = {
  SELL: 'SELL',
  REGISTER_POSITION: 'REGISTER_POSITION',
  DISCOUNT_DOCUMENT_POSITION: 'DISCOUNT_DOCUMENT_POSITION',
  POSITION_TAX: 'POSITION_TAX',
  DOCUMENT_OPEN: 'DOCUMENT_OPEN',
  DOCUMENT_CLOSE: 'DOCUMENT_CLOSE',
  PAYMENT: 'PAYMENT',
  DISCOUNT_POSITION: 'DISCOUNT_POSITION',
  DISCOUNT_DOCUMENT: 'DISCOUNT_DOCUMENT',
  OPEN_SESSION: 'OPEN_SESSION',
  CLOSE_SESSION: 'CLOSE_SESSION',
  PAYBACK: 'PAYBACK'
};

module.exports = appProperty;
