version: '2'
services:
  nats:
    image: nats
    stdin_open: true
    tty: true
    ports:
       - 4222:4222/tcp
       - 6222:6222/tcp
       - 8222:8222/tcp
    labels:
      io.rancher.container.pull_image: always
  mongo:
    image: mongo
    stdin_open: true
    tty: true
    ports:
       - 27017:27017/tcp
    labels:
      io.rancher.container.pull_image: always
