module.exports = `
  CREATE TABLE IF NOT EXISTS ${process.env.CLICKHOUSE_DB}.documents
  (
    userUuid String,
    date Date,
    documentUuid String,
    storeUuid String,
    deviceUuid String,
    deviceId String,
    documentType Enum8('SELL' = 1, 'PAYBACK' = 2, 'CASH_INCOME' = 3, 'CASH_OUTCOME' = 4, 'OPEN_SESSION' = 5, 'FPRINT' = 6, 'CLOSE_SESSION' = 7),
    closeDate DateTime, 
    openDate DateTime, 
    closeResultSum Float32, 
    closeSum Float32, 
    paymentSum Float32,
    oddMoney Float32,
    employeeUuid String,
    taxSum Float32,
    timeZone Int32,
    paymentType String,
    sessionUuid String,
    rrn String,
    totalDiscountPercent Int32,
    totalDiscountSum Float32,
    totalQuantity Float32,
    tareVolume Float32,
    alcoholByVolume Float32,
    alcoholProductKindCode Int32,
    balanceQuantity Float32,
    barcode String,
    productCode String,
    productUuid String,
    productName String,
    productType Enum8('NORMAL' = 1, 'ALCOHOL_MARKED' = 2, 'ALCOHOL_NOT_MARKED' = 3, 'SERVICE' = 4),
    costPrice Float32,
    mark String,
    measureName String,
    price Float32,
    quantity Float32,
    discountPositionPercent Int32,
    discountDocumentSum Float32,
    discountPositionSum Float32,
    taxResultPrice Float32,
    taxResultSum Float32,
    resultTaxSum Float32,
    tax Enum8('NO_VAT' = 1, 'VAT_10' = 2, 'VAT_18' = 3, 'VAT_0' = 4, 'VAT_18_118' = 5, 'VAT_10_110' = 6),
    taxPercent Float32,
    taxRateCode String,
    number Int32
  ) ENGINE = MergeTree(date, (date, documentUuid), 8192)
`;
